name: auto-merge

on: 
  workflow_call:
    inputs:
      target-repo:
        description: "The target repo on which this workflow should run"
        required: true
        type: string
    secrets:
      GH_TOKEN:
        description: 'Personal access token passed from the caller workflow'
        required: true

jobs:
  auto-merge:
    if: github.repository == inputs.target-repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-dependabot-auto-merge@70c9f0a176a7f7bf7c526d0da1d37d6c21e65329  # v2, as of 2021-11-26
        with:
          target: minor
          github-token: ${{ secrets.GH_TOKEN }}
