name: linter-js

on: 
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: Default GitHub token
        required: true

jobs:
  linter-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
