name: publish-vscode-extension

on: 
  workflow_call:
    secrets:
      VSCODE_MARKETPLACE_TOKEN:
        description: 'Personal access token from the VSCode marketplace'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCODE_MARKETPLACE_TOKEN"
        env:
          VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
