name: publish-vscode-extension

on:
  workflow_call:
    inputs:
      target-repo:
        description: The repo to run this action on. This is to prevent actions from running on forks unless intended.
        required: true
        type: string
    secrets:
      VSCODE_MARKETPLACE_TOKEN:
        description: "Personal access token from the VSCode marketplace"
        required: true

jobs:
  publish:
    if: github.repository == inputs.target-repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCODE_MARKETPLACE_TOKEN"
        env:
          VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
