name: set-default-labels

on:
  workflow_call:
    inputs:
      should-delete-labels:
        description: 'Delete labels that are not in the list'
        default: false
        required: false
        type: boolean

jobs:
  set-default-labels:
    name: SetDefaultLabels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
      - uses: lannonbr/issue-label-manager-action@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete: ${{ inputs.should-delete-labels }}
